ElunaEventMgr.cpp, HookMgr.cpp, LuaEngine.h
Needed for packet hooks.
Packet hooks will get some changes soon.
=> Eluna add mutex lock for hook calls

ElunaBinding.h, ElunaEventMgr.cpp, ElunaUtility.h, HookMgr.cpp, LuaEngine.cpp, LuaEngine.h
Rewriting hooks for new systems
Do not merge yet.
=> Hookmgr cleanup

ElunaBinding.h, ElunaEventMgr.cpp, ElunaEventMgr.h, GlobalMethods.h, LuaEngine.cpp, LuaEngine.h, PlayerHooks.cpp, ServerHooks.cpp, WorldObjectMethods.h, extensions/StackTracePlus/LICENSE, extensions/StackTracePlus/README.md, extensions/StackTracePlus/StackTracePlus.ext, extensions/_Misc.ext
Add StackTracePlus, Rewrite not to recreate eluna on reload
Needs config options created and checked.
Waiting for testing and look over.
=> Add StackTracePlus, Rewrite not to recreate eluna on reload

CreatureMethods.h, ElunaIncludes.h, GlobalMethods.h, GuildMethods.h, ItemMethods.h, LuaFunctions.cpp, PlayerMethods.h
Add the baseline support for Mangos Four support
- Tweaked a little bit of logic here and there to simplify things a bit
=> Add Mangos Four support

CreatureMethods.h, LuaFunctions.cpp, PlayerMethods.h, UnitMethods.h
Only tested on TC 3.3.5
Sorry if I spammed your dashboard with fork notifications
=> Fixed player:HasTalent, changed unit:GetCreatureType description, added creature:GetCreatureFamily

GlobalMethods.h
With the latest commits on AC, ban manager was updated, this PR will fix all build errors and repairs ban function.
=> Ban manager fix

GlobalMethods.h, GuildMethods.h
Repairs build for https://github.com/azerothcore/azerothcore-wotlk/pull/2454
=> AzerothCore

UnitMethods.h, WorldObjectMethods.h
Fix Mod Eluna AzerothCore
https://github.com/azerothcore/azerothcore-wotlk/pull/2454
=> Acore - rename namespaces and macros to acore

GlobalMethods.h, GuildMethods.h, ItemMethods.h, PlayerMethods.h
Ungroups Trinity from AzerothCore when necessary
Replaces SQLTransaction by CharacterDatabaseTransaction
=> Trinity SQLTransaction

CreatureMethods.h
I believe this will fix the build error https://github.com/azerothcore/azerothcore-wotlk/pull/2858 currently has
=> Update CreatureMethods.h for ACore PR

CreatureMethods.h, GlobalMethods.h, GuildMethods.h, ItemMethods.h, PlayerMethods.h
Add KickPlayer reason for Trinity
=> Update GlobalMethods and PlayerMethods

LuaFunctions.cpp, PlayerMethods.h
I think is a nice idea to add SetAchievement to Eluna.
This works 100% for TC & AC
=> Add SetAchievement to Eluna

.github/workflows/build.yml
This should make AC build faster for us. (new: 23 min, old: 39 min)
=> Try PCH=ON CCACHE=OFF

LuaFunctions.cpp, PlayerMethods.h
Allows player to learn all recipes for an specified skill id. (.learn all recipes xxxx)
Create an pet from a creature with given id that will get the level of the player.
=> Implement LearnAllRecipes and CreatePet player methods

GlobalMethods.h, Hooks.h
Adds and fixes documentation related to return values of event handler functions.
Closes https://github.com/ElunaLuaEngine/Eluna/issues/333
=> Document undocumented return values of bound event functions

GlobalMethods.h, WorldObjectMethods.h
=> Rename some defines 

GlobalMethods.h, GuildMethods.h
- Switch to new threading system
- Part https://github.com/azerothcore/azerothcore-wotlk/pull/4821
=> feat(GlobalMethods/AzerothCore): switch to new threading system

CreatureMethods.h, LuaFunctions.cpp
My first Git PR. Let me know if I did anything wrong. :)
=> Add IsDungeonBoss

CreatureMethods.h, LuaFunctions.cpp
Here's the function you suggested. :)
Tested with:
`local function OnEnterCombat(event, player, enemy)
print(enemy:GetName().." extra flags are: "..enemy:GetExtraFlags())
end
RegisterPlayerEvent(33, OnEnterCombat)`
On AC: "Rhahk'Zor extra flags are: 268435456" (Rhahk'Zor's flags_extra is 0 in the database)
=> Add Creature GetExtraFlags()

BindingMap.h, CorpseMethods.h, CreatureMethods.h, ElunaUtility.h, GameObjectMethods.h, GlobalMethods.h, GroupHooks.cpp, GroupMethods.h, GuildMethods.h, ItemHooks.cpp, LuaEngine.cpp, LuaEngine.h, MapMethods.h, ObjectMethods.h, PlayerHooks.cpp, PlayerMethods.h, ServerHooks.cpp, UnitMethods.h, WorldPacketMethods.h
Please - merge it once https://github.com/azerothcore/azerothcore-wotlk/pull/4885 is merged.
=> Implemented ObjectGuid support for AzerothCore.

PacketHooks.cpp
This should be PACKET_EVENT_ON_PACKET_RECEIVE not PACKET_EVENT_ON_PACKET_SEND
=> fix: wrong packet value in OnPacketReceiveOne

CreatureMethods.h, LuaFunctions.cpp
Implements the setter Creature:SetRegeneratingHealth
=> Implement: Creature:SetRegeneratingHealth

UnitMethods.h, WorldObjectMethods.h
https://github.com/azerothcore/azerothcore-wotlk/pull/6043
=> chore(Misc): acore -> Acore

UnitMethods.h, WorldObjectMethods.h
https://github.com/azerothcore/azerothcore-wotlk/pull/6113
=> chore: AzerothCore Cell::VisitAllObjects

LuaFunctions.cpp, UnitMethods.h
This PR adds `Unit:SetInCombatWith(enemy)`
=> Add Unit::SetInCombatWith()

CreatureMethods.h, LuaFunctions.cpp
Added the
```pUnit:SetreactState(x)```
To the exposed methods in ```CreatureMethods.h```
Takes as input:
```C++
enum ReactStates
{
REACT_PASSIVE    = 0,
REACT_DEFENSIVE  = 1,
REACT_AGGRESSIVE = 2
};
```
=> [Feature] Exposed SetReactState

ElunaIncludes.h, ElunaQueryMethods.h, ElunaUtility.h, GlobalMethods.h, ItemMethods.h, LuaEngine.h
- Replace `GitRevision::GetDate()` to `GitRevision::GetFullVersion()`
- Add support `GitRevision` for AC
- Add support AC dynamic linking
- Add support new api db (like TC)
Merge only after https://github.com/azerothcore/azerothcore-wotlk/pull/5611
=> chore(Misc): make AzerothCore new api support

CreatureMethods.h, ElunaIncludes.h, GlobalMethods.h, UnitMethods.h
https://github.com/azerothcore/azerothcore-wotlk/pull/6910
=> fix: Azerothcore mgr rename

UnitMethods.h
Merge it once https://github.com/azerothcore/azerothcore-wotlk/pull/7244 is merged on AC.
=> Buildfix for AzerothCore.

PlayerMethods.h, UnitMethods.h
Required after: https://github.com/azerothcore/azerothcore-wotlk/pull/8708
=> fix: AzerothCore SetFaction/GetFaction updates

AuraMethods.h, BattleGroundMethods.h, CreatureMethods.h, ElunaCreatureAI.h, ElunaEventMgr.cpp, ElunaIncludes.h, ElunaInstanceAI.h, ElunaTemplate.h, ElunaUtility.cpp, ElunaUtility.h, GameObjectMethods.h, GlobalMethods.h, GossipHooks.cpp, GroupMethods.h, ItemMethods.h, LuaEngine.h, LuaFunctions.cpp, PlayerMethods.h, UnitMethods.h, WorldObjectMethods.h, WorldPacketMethods.h
Currently works with CMaNGOS TBC and WotLK cores that are appropriately modified to add functions.
=> Changes to make engine compatible with current CMaNGOS

LuaFunctions.cpp, PlayerMethods.h
`Player:GetMailItem(guid)`: Returns a mailed `Item` by guid.
=> feat(PlayerMethods): expose GetMItem

GroupMethods.h, LuaFunctions.cpp
=> feat(GroupMethods): Expose IsLFGGroup()

GlobalMethods.h
All 3 cores of Cmangos have had an additional argument implemented for DB loads.
=> Changes to match new Cmangos DB load updates

GroupMethods.h, PlayerMethods.h
Core rework across all 3 cores have resulted in some functions changing names/case.
=> Update function names for recent CMangos updates

.github/workflows/build.yml
=> Configure CMangos Autobuild

ElunaCreatureAI.h, GroupMethods.h
-Fix build error with PCH off
-Update function name to match core update
=> Fix a few build issues

.github/workflows/build.yml
https://github.com/ElunaLuaEngine/Eluna/pull/421
=> Update auto build script to reference new repositories

GlobalMethods.h
Update defines to use updated functions for CMaNGOS based cores
=> Creature Create and GO Create functions changed in core

ElunaEventMgr.h, ElunaIncludes.h, ElunaUtility.cpp
Recent file restricting required updates to include paths.
=> Update include directives for recent CMaNGOS restructuring

ElunaCompat.cpp, ElunaCompat.h, ElunaTemplate.h, lmarshal.cpp
This contains the required changes to Eluna for the new LuaJIT support.
=> New Lua dependency

CMangos/CreatureMethods.h, CMangos/GlobalMethods.h, CMangos/GroupMethods.h, CMangos/GuildMethods.h, CMangos/ItemMethods.h, CMangos/MapMethods.h, CMangos/PlayerMethods.h, CMangos/QuestMethods.h, CMangos/UnitMethods.h, CMangos/WorldObjectMethods.h
Fix CMaNGOS specific functions per expansion
=> CMaNGOS specific fixes

.github/workflows/build.yml
-Add Cata Preservation Project(TC based) to CI check
=> Update CI build file

ElunaConfig.cpp, ElunaCreatureAI.h, ElunaLoader.cpp, LuaEngine.cpp, VMangos/AuraMethods.h, VMangos/BattleGroundMethods.h, VMangos/CorpseMethods.h, VMangos/CreatureMethods.h, VMangos/ElunaQueryMethods.h, VMangos/GameObjectMethods.h, VMangos/GlobalMethods.h, VMangos/GroupMethods.h, VMangos/GuildMethods.h, VMangos/ItemMethods.h, VMangos/MapMethods.h, VMangos/ObjectMethods.h, VMangos/PlayerMethods.h, VMangos/QuestMethods.h, VMangos/SpellMethods.h, VMangos/UnitMethods.h, VMangos/WorldObjectMethods.h, VMangos/WorldPacketMethods.h
VMaNGOS doesn't use Boost libraries so must use std::filesystem when its VMaNGOS.
=> Updates for VMaNGOS to multistate

.github/workflows/build.yml, .github/workflows/documentation.yml, CMangos/GlobalMethods.h, ElunaUtility.h, Hooks.h, ItemHooks.cpp, LuaEngine.h, TrinityCore/GlobalMethods.h
Reverts ElunaLuaEngine/Eluna#461
This wasn't meant to be a squash..
=> Revert "Update modules branch"

CMangos/CreatureMethods.h, Mangos/CreatureMethods.h, TrinityCore/CreatureMethods.h, VMangos/CreatureMethods.h
Add new method for issue : https://github.com/ElunaLuaEngine/Eluna/issues/407
=> Add Creature:RemoveFromWorld

methods/CMangos/PlayerMethods.h, methods/Mangos/PlayerMethods.h, methods/TrinityCore/PlayerMethods.h, methods/VMangos/PlayerMethods.h
to enable Lua scripts gossip control.
=> Add method
