ElunaLuaEngine/Eluna

MapMethods.h, PlayerMethods.h, UnitMethods.h
Fix the following compiler warnings, which is necessary to include Eluna into the AzerothCore Travis run (see https://github.com/azerothcore/mod-eluna-lua-engine/pull/11):
```
LuaEngine/UnitMethods.h:1496:14: fatal error: unused variable 'forced' [-Wunused-variable]
bool forced = Eluna::CHECKVAL<bool>(L, 4, false);
```
```
LuaEngine/UnitMethods.h:2279:16: fatal error: unused variable 'lang' [-Wunused-variable]
uint32 lang = Eluna::CHECKVAL<uint32>(L, 3);
```
```
LuaEngine/PlayerMethods.h:2475:38: fatal error: unused parameter 'L' [-Wunused-parameter]
int LeaveBattleground(lua_State* L, Player* player)
```
```
LuaEngine/PlayerMethods.h:3496:14: fatal error: unused variable 'update' [-Wunused-variable]
bool update = Eluna::CHECKVAL<bool>(L, 3, true);
```
```
LuaEngine/MapMethods.h:264:39: …
```
=> fix some compiler warnings about unused variables

CreatureMethods.h, GroupMethods.h, PlayerMethods.h
Sorry, but I forgot in PR #288 that AC not only checks clang 7 but also clang 3.8 compilation. This PR fixes the following compiler warnings:
```
modules/mod-eluna-lua-engine/LuaEngine/PlayerMethods.h:3989:20: fatal error: unused variable 'invitedgroup' [-Wunused-variable]
if (Group* invitedgroup = player->GetGroupInvite())
```
```
modules/mod-eluna-lua-engine/LuaEngine/PlayerMethods.h:3991:20: fatal error: unused variable 'invitedgroup' [-Wunused-variable]
if (Group* invitedgroup = invited->GetGroupInvite())
```
```
modules/mod-eluna-lua-engine/LuaEngine/CreatureMethods.h:596:30: fatal error: unused variable 'spellInfo' [-Wunused-variable]
if (SpellInfo const* spellInfo = sSpellMgr->GetSpellInfo(spell))
```
```
modules/mod-eluna-lua-engine/LuaEngine/GroupMethods.h:138:20: fatal error: …
```
=> fix some compiler warnings about unused variables, part 2

GuildMethods.h
`DeleteMember` is declared as follows in AzerothCore:
```c++
void DeleteMember(uint64 guid, bool isDisbanding = false, bool isKicked = false, bool canDeleteGuild = false);
```
so the first parameter should be `guid`, not an `SQLTransaction`
=> fix(AzerothCore): correct mistake in GuildMethods.h

GlobalMethods.h
Currently Global:SendMail returns nothing.
In my issue https://github.com/ElunaLuaEngine/Eluna/issues/346 i suggest to let it return the guid's of the items created.
~~Not knowing C++ well, i added code which can return the guid of the first item created by SendMail. 
It is kind of a workaround, so any advice in how to return all item GUIDs is appreciated.~~
The latest commit makes the SendMail command return all GUIDs of the created items, ~~only for Azerothcore.~~ for all supported cores.
=> Global:SendMail should return the GUIDs of the created items

ElunaCreatureAI.h
On Trinity, ElunaCreatureAI called JustAppeared() while the core also called JustAppeared(), resulting in two events getting triggered.
Fixes #312
=> Fixed Creature_Event_On_Spawn getting called twice

LuaFunctions.cpp, PlayerMethods.h
* Added `Player::SendUpdateWorldState(field, value)`
* Fixed missing argument in documentation for `Player::GetGossipTextId(object)` while I was at it
=> Add Player::SendUpdateWorldState()

GlobalMethods.h, LuaFunctions.cpp, MapMethods.h
* Added `RunCommand(command)` to run a server CLI command
* Fixed missing return value in documentation for `Map::GetWorldObject(guid)` while I was at it
=> Add RunCommand()

LuaEngine.cpp
- Remove `ace` inherited for AzerothCore
---
@Rochet2 I think you can merge this now
=> feat(Engine): add support USING_BOOST macro for AC

GossipHooks.cpp
Fix a case where returning true from the gossip select hook does not allow default action to continue as intended because the gossip menu is cleared when the hook is triggered.
This preservers old behavior of clearing the menus while fixing the issue.
Fixes https://github.com/ElunaLuaEngine/Eluna/issues/404
=> Restore gossip menu after lua script

WorldObjectMethods.h
`TempSummon* WorldObject::SummonCreature` takes std::chrono::milliseconds as an argument, not seconds 
(unlike `GameObject* WorldObject::SummonGameObject` which takes std::chrono::seconds)
[TempSummon* WorldObject::SummonCreature(uint32 id, float x, float y, float z, float o /*= 0*/, TempSummonType despawnType /*= TEMPSUMMON_MANUAL_DESPAWN*/, Milliseconds despawnTime /*= 0s*/, bool visibleBySummonerOnly /*= false*/)](https://github.com/ElunaLuaEngine/ElunaTrinityWotlk/blob/06136c07451ccdf8aae0418aa48568b1983d0a66/src/server/game/Entities/Object/Object.cpp#L2048)
Casting uint32 -> Seconds -> Milliseconds makes a * 1000 happen so if you wanted to spawn a creature for 5000 milliseconds you end up spawning it for 5000000 milliseconds.
Currently doing a WorldObject:SpawnCreature(..., …
=> Fix WorldObject:SpawnCreature despawnTimer for TrinityCore

ElunaIncludes.h, GlobalMethods.h, UnitMethods.h
Recent core changes have required these minor changes. Also includes an added command handler as the existing ones were getting excluded due to a lack of precompiler directive for CMaNGOS. Core changes to protect against a nullptr crash in the core has already been pushed for Classic, TBC, WotLK cores
=> Updates for changes to CMaNGOS cores

.github/workflows/build.yml, CMangos/AuraMethods.h, CMangos/BattleGroundMethods.h, CMangos/CorpseMethods.h, CMangos/CreatureMethods.h, CMangos/ElunaQueryMethods.h, CMangos/GameObjectMethods.h, CMangos/GlobalMethods.h, CMangos/GroupMethods.h, CMangos/GuildMethods.h, CMangos/ItemMethods.h, CMangos/MapMethods.h, CMangos/ObjectMethods.h, CMangos/PlayerMethods.h, CMangos/QuestMethods.h, CMangos/SpellMethods.h, CMangos/UnitMethods.h, CMangos/VehicleMethods.h, CMangos/WorldObjectMethods.h, CMangos/WorldPacketMethods.h, ElunaIncludes.h, GossipHooks.cpp
Cleaned up all the CMaNGOS header files. Eliminated all other cores from defines. Also added CMaNGOS Cata fork compatibility. Updated CI build file to newer actions and add CMaNGOS Cata build check
=> CMaNGOS specific cleanups and CI update

ElunaCreatureAI.h, ElunaIncludes.h, ElunaUtility.cpp, GroupHooks.cpp, GuildHooks.cpp, ItemHooks.cpp, LuaEngine.h, PlayerHooks.cpp, README.md, TrinityCore/BattleGroundMethods.h, TrinityCore/CreatureMethods.h, TrinityCore/GameObjectMethods.h, TrinityCore/GlobalMethods.h, TrinityCore/GuildMethods.h, TrinityCore/ItemMethods.h, TrinityCore/MapMethods.h, TrinityCore/PlayerMethods.h, TrinityCore/QuestMethods.h, TrinityCore/UnitMethods.h, TrinityCore/VehicleMethods.h, TrinityCore/WorldObjectMethods.h
Adds support for The Cataclysm Preservation Project. Updated CI build file to include check against this core will be added in a separate PR since it will address a few other issues with the CI builds.
=> Add Cata Preservation Project

CMangos/UnitMethods.h, Mangos/UnitMethods.h, TrinityCore/UnitMethods.h, VMangos/UnitMethods.h
Adds a new method to add and remove mechanic immunities. See https://github.com/azerothcore/mod-eluna/pull/167
Tested on AC with:
```lua
local function ImmunityOff(eventid, delay, repeats, creature)
creature:SetImmuneTo(26, false)
creature:SendUnitSay("I am interruptable now.", 0)
end
local function Cast(eventid, delay, repeats, creature)
creature:CastSpell(creature, 57775, false)
end
local function EnterCombat(event, creature, target)
creature:SetImmuneTo(26, true)
creature:SendUnitSay("You can not interrupt me.", 0)
creature:RegisterEvent(Cast, 5500, 0)
creature:RegisterEvent(ImmunityOff, 15000, 1)
end
local function LeaveCombat(event, creature)
creature:RemoveEvents()
end
RegisterCreatureEvent(113, 1, EnterCombat)
RegisterCreatureEvent(113, 2, LeaveCombat) -- OnLeaveCombat …
```
=> add unit method SetImmuneTo

ElunaTemplate.h, LuaEngine.cpp, LuaFunctions.cpp, LuaValue.cpp, LuaValue.h
* Improved memory allocation patterns for ElunaObject and LuaVal (one alloc per call instead of two)
* Reworked LuaVal internals to remove dynamic allocation for variant and string, deep clones are now only done explicitly by `clone()` member
* Improve __tostring for LuaVal for WrappedMap case
=> Improved memory allocation patterns for ElunaObject and LuaVal

CMakeLists.txt
Issue: target_compile_definitions(lualib PUBLIC LUA_COMPAT_MODULE) results in a CMake error when running with luajit.
Solution: The proposed solution is to guard this definition with a condition to ensure lualib isn't an IMPORTED target before adding the definition.
=> Fix error target_compile_definitions on Cmake with Luajit

CMangos/ElunaQueryMethods.h, CMangos/GlobalMethods.h, ElunaTemplate.h, ElunaUtility.h, InstanceHooks.cpp, LuaEngine.cpp, LuaFunctions.cpp, Mangos/ElunaQueryMethods.h, Mangos/GlobalMethods.h, PacketHooks.cpp, ServerHooks.cpp, TrinityCore/AuraMethods.h, TrinityCore/GameObjectMethods.h, TrinityCore/GlobalMethods.h, TrinityCore/PlayerMethods.h, VMangos/ElunaQueryMethods.h, VMangos/GlobalMethods.h
Extracted from my other pull request
Simple test showing that query results are still freed properly (/lol then .reload eluna to force gc)
```lua
local function OnTextEmote(event, player, textEmote, emoteNum, guid)
for k, v in pairs(CharDBQuery("SELECT 1 as dummy"):GetRow()) do
player:SendBroadcastMessage(k.." = "..v)
end
end
RegisterPlayerEvent(24, OnTextEmote)
```
=> Removed additional indirection when pushing 64 bit integers, ObjectGuids, query results and WorldPackets

LuaEngine.cpp
Previously the precompilation cache was not used for scripts that were loaded through require. Now require first always tries to load precompiled script and otherwise falls back to default loading.
As require is now able to access the precompiled scripts, we can default to it for running scripts.
=> Optimize require, streamline script running to always just call require

LuaEngine.cpp, LuaEngine.h
We now push the function to stack only once and never shift all function call arguments around.
=> Optimize stacktrace functionality

BindingMap.h, LuaEngine.cpp, methods/TrinityCore/ElunaQueryMethods.h, methods/TrinityCore/PlayerMethods.h
Allows using less #ifdefs when trying to support master branch
Additional changes for ElunaQuery:GetRow() 
* add missing unsigned and floating point types support (since TrinityCore/TrinityCore@24fc0dcb1ee627cdec5ff5670a85050afc62d281)
* switched it to use new GetFieldMetadata, making patching Field and QueryResult in ElunaLuaEngine/ElunaTrinityWotlk unneccessary
Requires latest changes in 3.3.5 branch to compile
=> Improve compatibility with TrinityCore master branch

ElunaConfig.cpp, ElunaConfig.h, ElunaLoader.cpp, ElunaLoader.h, LuaEngine.cpp
This implements async script cache reloading in a separate thread to the main thread. See https://github.com/ElunaLuaEngine/Eluna/issues/487
=> Asynchronous script cache reload functionality

ElunaConfig.cpp, ElunaCreatureAI.h, ElunaEventMgr.cpp, ElunaEventMgr.h, ElunaIncludes.h, ElunaInstanceAI.cpp, ElunaInstanceAI.h, ElunaLoader.cpp, ElunaLoader.h, ElunaTemplate.h, ElunaUtility.cpp, ElunaUtility.h, LuaEngine.cpp, LuaEngine.h, LuaFunctions.cpp, hooks/CreatureHooks.cpp, hooks/GameObjectHooks.cpp, hooks/GossipHooks.cpp, hooks/GuildHooks.cpp, hooks/ItemHooks.cpp, hooks/PacketHooks.cpp, hooks/PlayerHooks.cpp, hooks/ServerHooks.cpp, hooks/VehicleHooks.cpp
Will require cmake changes core side to switch from the old TBC/WOTLK etc definitions to a generic EXPANSION definition
=> Preprocessor cleanup

LuaEngine.cpp, LuaEngine.h
This reverts commit 24cae109a5b5bcbbd59e3c09e553322a85793626.
Fixes crash with hook calls nested within method calls when Eluna.TraceBack is true.
If you have this issue currently, then set Eluna.TraceBack to false in Eluna server config or update your core so it has this fix in.
=> Revert "Optimize stacktrace functionality (#477)"
